name: Run Python Script Patcher on Commit

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./script-patcher/requirements.txt

      - name: Authenticate with Google API
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}" | base64 --decode > credentials.json

      - name: Debug the contents of credentials.json
        run: |
          cat credentials.json

      - name: Run the index script
        run: |
          python script-patcher/index.py
